### ISSUE TITLE
Questions about TITLE class

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#12]
@kermitt2 what are the boundaries on which annotate a person title. 
For example:  `president`, `founder`, `chairman`, `member`..

See examples: 
1.  member

```
He	O
was	O
one	O
of	O
the	O
outstanding	O
activists	O
in	O
the	O
Zionist	B-ORGANISATION
movement	ORGANISATION
in	O
Bulgaria	B-LOCATION
:	O
he	O
served	O
as	O
a	O
member	O
of	O
the	O
Central	B-ORGANISATION
Committee	ORGANISATION
of	O
the	O
Zionist	B-ORGANISATION
Union	ORGANISATION
in	O
Bulgaria	B-LOCATION
,	O
1919	B-PERIOD
-	PERIOD
1923	PERIOD
;	O
```

2. Example 2: `chairman`

```
he	O
held	O
five	B-MEASURE
terms	O
of	O
office	O
as	O
the	O
representative	O
to	O
the	O
World	B-ORGANISATION
Zionist	ORGANISATION
Congress	ORGANISATION
;	O
he	O
served	O
as	O
the	O
# is it worth it to annotate this? 
chairman	B-TITLE
of	O
the	O
Zionist	B-ORGANISATION
Organization	ORGANISATION
in	O
Sofia	B-LOCATION
```

3.  `founders`? 

```
he	O
was	O
one	O
of	O
the	O
# shall we annotate this? 
founders	B-TITLE
of	O
the	O
Revisionist	B-ORGANISATION
movement	ORGANISATION
in	O
Bulgaria	B-LOCATION
and	O
its	O
# check this
chairman	B-TITLE
from	B-PERIOD
1925	PERIOD
-	PERIOD
1935	PERIOD
.	O
```

**Comment by kermitt2** [comment]
Best start is the Wikipedia page:
https://en.wikipedia.org/wiki/Title

Intuitively I am rather for a relatively loose definition and thus would say yes for all your 3 cases. Then we have to check if this policy is solid enough with more examples.

**Comment by everzeni** [comment]
what about `President of the United States` ?

**Comment by everzeni** [comment]
cf also #33

**Comment by lfoppiano** [comment]
Regarding the discussion of yesterday (2nd May) I try to give some formalism: 
1. The name of a person doesn't change -> Barak Obama is always the same person (or there are multiple Barak Obama, but that's another story) -> `PERSON`
2. The title (as institutional role) is almost always also a person, so using one or the other might be correct. For all these examples we should annotate them as `TITLE`, e.g. `The President of the United States`, `The Chinese Prime minister`, etc
3. In case of the largest entity match of `TITLE PERSON`, the priority goes to the `PERSON` class, e.g. `The President of the United States Barak Obama`. 

What do you think?

**Comment by everzeni** [comment]
It seems Ok! It reflects the fact that if the name of the person is mentioned, the semantic focus is on the person, who is always the same (regardless of his/her title). If there is only the title, the focus is on this title.

I just wonder if we really want to annotate as `TITLE` these different cases:
- Who is Donald Trump? He is the **President of the US**.
- he is **CEO** of this company
- The **President of the US** said blablabla.

I feel 1) and 2) are more `TITLE` than 3)... I don't know if that makes sense :grimacing:

**Comment by kermitt2** [comment]
I think the difference is that for 1) and 2) `TITLE` is introduced as attribute, and for 3) it is used to refer to an actual person. However I think it is relevant to annotate `TITLE` in all these cases, because in 3) it is also the fact that someone has a `TITLE` which is emphasized.  

(I also don't know if it makes sense ;) )

**Comment by everzeni** [comment]
Regarding the discussion we had on Slack about whether job names should be annotated as TITLEs, I'll try to recap:

1) job names, in general, are not annotated as TITLE, for example: _economist, computer scientist, carpenter_

2) in the special case of the `National State Archivist` (of Belgium) -> here `archivist` is `TITLE` because it's an official position (lhe guy probably don't spend his days classifying and organizing access to documents...)

3) sometimes a job might be a TITLE? For example `doctor`...  I wonder what to do with `engineer`? It's also kind of a TITLE... what do you think?

**Comment by wigdan** [comment]
Although some of the jobs such as Secretary of State, MP, or Prime Minister are clearly TITLE, we don't annotate them as TITLE, when applying the large entity match principle, should they come with the PERSON name.
I think, we need a clear cut strategy or some specific rules to guide us.

**Comment by kermitt2** [comment]
* About Engineer, it depends on the legislation of the country where it is used. In some countries it is strictly regulated (like Germany with the Dr. Ing. everywhere, or France), and it is normally illegal to claim to be an engineer without having an Engineer diploma under certain conditions (in France, to come from a stated authorized/validated engineer school). It's exactly like the title Doctor, it comes from the diploma, not as a profession. When related to these countries we can annotate them as `TITLE` I think. 

Then in the UK state-regulated engineers are called "chartered engineer", engineer is the profession. In the US it is not regulated at all, "engineer" always refers to the job - so no annotation. 

* Regarding _Secretary of State_, _MP_, or _Prime Minister_, I think it is clear following Luca's rules. In isolation they should be all annotated `TITLE`. The longest entity principle applies only when it is used in combination with the person name (_Prime Minister May_), then priority goes to `PERSON`. Or do I misunderstand something?

**Comment by ebenaissa** [comment]
> Members of the British Royal Family had fled to Ireland and the Isle of Man

We think that British Royal Family is a `PERSON_TYPE` same reason as we annotate Jews group _'role classified according to group membership'_  and Members is a `TITLE`  what is the priority between those two label ? My intuition is we annotate the whole as `PERSON_TYPE` like the priority between `TITLE` and `PERSON` 

```xml
<ENAMEX type="PERSON_TYPE">Members of the British Royal Family</ENAMEX> had fled to
<ENAMEX type="LOCATION">Ireland</ENAMEX>
```

**Comment by kermitt2** [comment]
@ebenaissa I would say exactly the same for the two points you raised 👍

**Comment by everzeni** [comment]
in this sentence:
> Eurozone laws would not necessarily apply to non-Eurozone EU members and the latter would not have to bail out troubled 

we are wondering if we should annotate:
```xml
- <ENAMEX type="INSTITUTION">EU</ENAMEX> members
- <ENAMEX type="TITLE">non-Eurozone EU members</ENAMEX> 
```
?

**Comment by lfoppiano** [comment]
I have though about it, I have a different view. 

I try to explain it:  
0. In both cases, `member` is not a person/group of people, therefore `TITLE` doesn't work here. 

case 1: EU members are the countries as part of the european union, so the annotation as you have written it makes sense. 

case 2: Being in the eurozone is like having a contract to adopt the euro. I would annotate it as: 

`non-<ENAMEX type="LEGAL">Eurozone EU members</ENAMEX>`

...either `LEGAL` or `CONCEPTUAL` since it's more a contract, I would go for `LEGAL` although I know it was designed more specifically for other type of entities (article 50, energy propulsion act, etc.)

I would exclude the `non` because it doesn't change the nature of the entity (President and non-President is still a title?)

What do you think?

**Comment by kermitt2** [comment]
Here is my analysis: _EU_ is an `INSTITUTION`, _Eurozone_ here, whatever its entity type is, is a modifier, so the largest entity principle gives `INSTITUTION` for the whole (_members_ and _non_ are common word and member is not an acceptable _TITLE_ here which would need to apply to a person):

```xml
non-<ENAMEX type="INSTITUTION">Eurozone EU</ENAMEX> members
```

Let's suppose _Eurozone_ appears alone somewhere, e.g. _ the Eurozone members are numerous_. The _Eurozone_ is a group of Nations binded by a treaty, it's a _monetary union_. So for me it would be the same as the _EU_ which is a _political union_. So I would annotate like that:

 ```xml
the <ENAMEX type="INSTITUTION">Eurozone</ENAMEX> members are numerous
```

**Comment by everzeni** [comment]
While reviewing each others annotations, we found we are confused about some aspects of TITLE:

1) `leader`
To which point `leader` is a TITLE? In the wikipedia page it's only mentioned as an aristocratic title, for cases like the `Great Leader` of North Korea or the `Supreme Leader` of Iran. This is way different from `leader of the Zionist movement`, don't you think? so:

      1.1 should we annotate it in things like `leader of the Zionist movement` or `Nazi leader`?

      1.2 if yes, should we also annotate it when it's plural, for example `council leaders [of a ghetto council]`, `party leaders`, `Jewish resistance leaders`


2) `officers`
`officer` can be a TITLE and it's mentioned in the Wikipedia page. However in some cases where it's plural, we are doubting. Some examples:
     > 2.1 one **Wehrmacht officer** told his men (...) -> ok for TITLE here
     > 2.2 **Wehrmacht officers** told their soldiers to target [...] Jewish Bolshevik -> TITLE?
     > 2.3 The prisoners killed 11 **German SS officers** -> TITLE?
     > 2.4 High Command, comprising several categories of **senior military officers**. -> too generic?

3) `member`
In the Wikipedia page, the cases of `member` being a title are:
     - members of legislatures like MP (Member of Parliament) or MC (Member of Congress)
     - Member and Chairman, for members of quasi-judicial boards (`Board member` at a company, for example)

     It seems to exclude a lot of other things, and in most cases we don't really understand why `member` should be a TITLE. Here are some examples:
     > 3.1 **members** of the FPO fled to the forest 
     > 3.2 the escapees were dressed as **members** of the SS-Totenkopfverbände
     > 3.3 people are being exterminated, says every party **member**

Thank you!

**Comment by kermitt2** [comment]
1. I would say `leader` mentions here correspond to the common usage of this word, without any special characteristics so I would not annotate them

2. I think for being consistent it's better to annotate the plurials too. 

3. same as for 1, it's really the common sense/usage of member.
