### ISSUE TITLE
PERIOD intervals not structured

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#13]
Given a sentence starting from `As early as the 1930s, [...]`, does it make sense to annotate this chunk as `PERIOD`
```
As	B-PERIOD
early	PERIOD
as	PERIOD
the	PERIOD
1930s	PERIOD
,	O
```

 or as it's annotated in the example? 

```
As	O
early	O
as	O
the	O
1930s	B-PERIOD
,	O
Benjamin	B-PERSON
Arditti	PERSON
expressed	O
interest	O
in	O
the	O
history	O
of	O
the	O
Jews	B-PERSON_TYPE
of	O
Bulgaria	B-LOCATION
;	O
```

**Comment by kermitt2** [comment]
I would say no because it simply qualifies the period but not changed it. 

As early as the 1930s = 1930s

**Comment by lfoppiano** [comment]
When there is an interval, we annotate `from` as part of the entity. 

What about other elements like 
- `since`: for example`It preserves moving pictures since 1919`, can be annotated with `since 1919` as `PERIOD`? 

- `during`: related to event can be a period: 
   1. `during the time of the Nazi occupation`: 
       - `during the time of the <ENAMEX type="EVENT">Nazi occupation</ENAMEX>` or 
      - `<ENAMEX type="PERIOD">during the time of the Nazi occupation</ENAMEX>`.
   2. `during the Czarist regime:
      - `<ENAMEX type="PERIOD">during the Czarist regime</ENAMEX>` or
      - `during the <ENAMEX type="LOCATION">Czarist regime</ENAMEX>` or 
     - `during the <ENAMEX type="EVENT">Czarist regime</ENAMEX>` or 

- `in`: In this example: `the staff, chiefs, mayors and their assistants, men who were born in 1919-1924, war prisoners, war refugees from Russia`. 
Should `in` be included in the entity `1919-1924`?

**Comment by kermitt2** [comment]
* since: I would indeed annotate also what qualify the range of period , so I would annotate _since_, similarly as _from_, as part of the entity. We don't have the same period type with and without the word _since_ or _from_

* during: In general I would not annotate during at all, it does not qualify an interval, just "locate" the predicate with respect to the interval

i. any event defines a period, but a period is not an event - so what useful I think is to annotate as EVENT

ii. difficult - I have no clear answer for the moment for this one...

* in: we have a clear interval without the _in_, it's like _during_ I think, not to be annotated as part of the entity.

**Comment by everzeni** [comment]
It seems to us that if we annotate `Nazi occupation` as `EVENT`, it should be the same class for `Czarist regime`.

**Comment by lfoppiano** [comment]
What about `after`, `before`? 

I have a couple of more cases: 
 1. `after 1930 there was a great boom` -> I tend to think that we should annotate `after 1930` (same would be for `before 1930 blablabla`)
 2. `7 years after the war there was a great boom` -> shall we annotate also `after`, though I think won't make sense because there is no starting point 

Maybe I'm overcomplicating things?

**Comment by kermitt2** [comment]
@lfoppiano it's not overcomplicating at all, good points to clarify `PERIOD` !

For me it's exactly like `since`, `from`, `before`, that's defining the period, so I would put both as part of the entity `PERIOD` : we need these words to translate the raw entity into the correct structured interval of time.

**Comment by everzeni** [comment]
What about `next` and `last`? For example:

> The <ENAMEX type="LOCATION">U.S.</ENAMEX> eventually establishes safe zones west of the <ENAMEX type="LOCATION">Rocky Mountains</ENAMEX> and spends much of the **next <ENAMEX type="PERIOD">decade**</ENAMEX> eradicating zombies in that region.</sentence>

We feel we should annotate it as PERIOD:
```xml
much of the <ENAMEX type="PERIOD">next decade</ENAMEX> eradicating zombies
```
1) what do you think for `next` / `last` ?

2) about the second example of @lfoppiano : `7 years after the war there was a great boom`. It seems to me that `7 years after` alone makes no sense as a PERIOD... It's different than `after 1930`. The time marker here is `after the war` and not only `after`... maybe we should annotate:
```xml
<ENAMEX type="PERIOD">7 years after the war</ENAMEX> there was a great boom
```
?

**Comment by kermitt2** [comment]
Thanks @everzeni I agree with both 👍

**Comment by everzeni** [comment]
question from Slack, should we annotate like `7 years after the war` these entities:

1) `Seven years after the outbreak began`
2) `7 years after the war`
?

I vote yes, what do you think?

**Comment by lfoppiano** [comment]
I also vote `yes`. 

Reality doesn't exists ;-)

**Comment by everzeni** [comment]
I realized I made a mistake writing my last comment, the second example was:

`Ten years after the official end of the zombie war`

The question was should we annotate it like `7 years after the war`, which would be:
```xml
<ENAMEX type="PERIOD">Ten years after the official end of the zombie war</ENAMEX>
```

**Comment by everzeni** [comment]
We have another example and we are doubting, I have two questions:

1) about my precedent comment, do you think we should annotate:
```xml
<ENAMEX type="PERIOD">Ten years after the official end of the zombie war</ENAMEX>
```

2) our other case is: 
> it would have allowed the <ENAMEX type="LOCATION">UK</ENAMEX> to withhold social benefits to new immigrants for the first four years after they arrived;

Do you think we should annotate:
```xml
it would have allowed the <ENAMEX type="LOCATION">UK</ENAMEX> to withhold social 
benefits to new immigrants for the <ENAMEX type="PERIOD">first four years after 
they arrived</ENAMEX>;
```
thanks!

**Comment by everzeni** [comment]
To complete my two previous comments...

We have another sentence and it made us think about the after "after" problem... Here is the sentence:
> The Treaties shall cease to apply to the State in question (...) **two years after the notification referred to in paragraph 2**

How about we decide to annotate inside the PERIOD the part « after **X**», but only if **X** is expressing an EVENT? For the recent sentences we discussed, it would lead to:

1) **INCLUDE "after X"**: `<ENAMEX type="PERIOD">7 years after the war</ENAMEX>`

2) **INCLUDE "after X"**: `<ENAMEX type="PERIOD">Ten years after the official end of the 
zombie war</ENAMEX>`

3) **EXCLUDE "after X"**: `withhold social benefits to new immigrants for the <ENAMEX 
type="PERIOD">first four years</ENAMEX> after they arrived`

4) **EXCLUDE "after X" and annotate MEASURE instead**: `The Treaties shall cease to apply 
to the State in question (...) <ENAMEX type="MEASURE">two years</ENAMEX> after the 
notification referred to in paragraph 2**`

What do you think?

**Comment by wigdan** [comment]
`mid afternoon on <ENAMEX type="PERIOD">27 June 2016</ENAMEX>`

Would you include (mid after noon) within the whole period?

**Comment by lfoppiano** [comment]
@everzeni regarding to your first comment, I agree with your proposal. I'm just wondering whether `2 years` is a `measure` or a `period`. I'm asking because I've seen an example of the same token classified as `period` in `EHRI_unit_il-002798-p_37.2.en.training.xml`.

@wigdan as you said, I agree not to include `mid afternoon on` in the whole period.

**Comment by kermitt2** [comment]
@wigdan @lfoppiano I would add _mid afternoon_ in the annotation, because it is part of the whole time expression: <ENAMEX type="PERIOD">mid afternoon on 27 June 2016</ENAMEX>

**Comment by wigdan** [comment]
the pound fell to a seven-year low against the dollar
what would be the appropriate annotation for seven-year?
it indicates time or period, but it comes with (low) which makes it as comparison or measure?
and thats makes me little confused...!

**Comment by kermitt2** [comment]
I would annotate seven-year as a `PERIOD`. I don't see any particular impact with _low_, given that we annotate time "measurement" as `PERIOD` anyway.

**Comment by everzeni** [comment]
@kermitt2 what do you think about this comment hereabove: https://github.com/kermitt2/grobid-ner/issues/13#issuecomment-302090399 ? thank you

**Comment by kermitt2** [comment]
@everzeni it looks convincing ! :+1:
