### ISSUE TITLE
MEASURE not measuring 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#14]
@kermitt2 To be 100% sure. The chunk: `one of the` is measuring nothing, therefore shall be annotated as `O`. Does it make sense?

```
he	O
was	O
one	O
of	O
the	O
founders	B-TITLE
of	O	
the	O	
Revisionist	B-ORGANISATION
movement	ORGANISATION
in	O
Bulgaria	B-LOCATION
```

**Comment by kermitt2** [comment]
yes it's rather a frozen expression than any expression of quantity, agree!

**Comment by lfoppiano** [comment]
What about the terms `first`, `second`, `third`, etc... 

Personally I would not consider them measures, as they are not measuring anything, but, on the other hand, they are indicating some cardinal positioning ...

**Comment by kermitt2** [comment]
These are __ordinal__ in linguistics, they can be view as ```MEASURE``` I think without too much doubt as they indicate a numerical order in a scale or measure of something that can be quantified (size, date, etc.). 

However, I think we should not consider referring expressions e.g. _of the two courses on linguistics, the _first_ is the less boring_, here I would not annotate _first_.

**Comment by everzeni** [comment]
I feel that this one: 
> there occurred a boycott of <ENAMEX type="PERSON_TYPE">Jewish</ENAMEX> businesses, which was the **first** national antisemitic campaign

is not to be annotated either, since it seems more like an equivalent of "for the first time" / "the beginning of" and not really an order in a scale or something quantified (different from "the first commandment", for example). 

Is that correct?

**Comment by lfoppiano** [comment]
@everzeni I think it's correct not to annotate it.

**Comment by everzeni** [comment]
While reviewing each other files, we found it's difficult to reach a consensus on ordinals, particularly `first`. It seems we need more precise criteria to work on, so I propose to annotate all the ordinals (even my above example `first national antisemitic campaign` as MEASURE, except:

- things like `among the first to be sent to concentration camps` or `one of the first` where there is no notion of scale but rather of "beginning"

- plural things like `the first jews to be deported`

What do you think?

**Comment by kermitt2** [comment]
I agree. Maybe the criteria here is: can we quantify (enumerate) what is "first"?

**Comment by everzeni** [comment]
Elias proposed another criteria, in addition with "can we quantify what is first?": can we replace "first" by "second". It seems to work and eliminate things like `one of the thirst`, `among the first`, `the first X to`.

What do you think?

**Comment by everzeni** [comment]
Ok so we keep this criteria (replacement by "second") until further notice.
