### ISSUE TITLE
entities of class PERSON_TYPE but referring to other entities (e.g. newspaper, problems,  etc.)

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#15]
There are some concept like Zionist, Jewish that are referred to people,

**Zionism**
From wikipedia: ```Zionism is the national movement of the Jewish people that supports the re-establishment of a Jewish homeland in the territory defined as the historic Land of Israel [...]```
1. `Zionist` if we refer to a person, should be `PERSON_TYPE`. 
2. In this case `Zionist` is referred to newspapers, would be corrected to annotate it as `CONCEPTUAL`? 

See example: 
```
Articles	O
from	O
European	B-NATIONAL
Zionist	B-CONCEPTUAL
newspapers	O
,	O
1901	B-PERIOD
-	PERIOD
1931	PERIOD
```

Another example (`Zionist events`): 
```
Issue	O
of	O
Haolam	B-MEDIA
newspaper	O
with	O
excerpts	O
on	O
Zionist	B-CONCEPTUAL
events	O
in	O
Europe	B-LOCATION
at	O
the	O
time	O
.	O
```

**Jews/Jewish**
Another example is referring to the `Jews`. In this chunk is referred to `problems`, it has been tagged as `NATIONAL` but it's incorrect, because the subject is not the nation or the place. 
What would be a more correct tag? 

```
Section	O	
of	O
the	O
L	O	B-MEDIA
'	O	MEDIA
echo	O	MEDIA
Sioniste	MEDIA
newspaper	MEDIA
with	O
reports	O
on	O
Jewish	B-NATIONAL
problems	O
in	O
Bulgaria	B-LOCATION
,	O
```

**Comment by kermitt2** [comment]
It's ```PERSON_TYPE``` I think for all these cases. The fact that we have newspapers, dishes, event or sport from/for this group of people does not make the group of people a different entity, it's just a modifier. 

However Zionism would be ```CONCEPTUAL```.

We could think of linguistic tests like substitutions to make the choice more systematic, for instance can we change Zionist with other group of people.

**Comment by lfoppiano** [comment]
What wouls be a valid sustitution for `zionist`? Is it more like `communist`? I was thinking in fact more something like `liberal` or `laburist`.

**Comment by kermitt2** [comment]
For me any of this, but it could be ```blond people```, ```diabetics```, etc. A newspaper for ```blond persons``` or ```muffin lovers``` does not make it conceptual?

**Comment by lfoppiano** [comment]
OK, I have one last example I forgot to add: 
When you have `Zionist movement`, can be considered like an `ORGANISATION`, as it's defined as `Zionist movement - a movement of world Jewry that arose late in the 19th century with the aim of creating a Jewish state in Palestine`

Here how we annotated: 

```
He	O
was	O
one	O
of	O
the	O
outstanding	O
activists	O
in	O
the	O
Zionist	B-ORGANISATION
movement	ORGANISATION
in	O
Bulgaria	B-LOCATION
```

or should be more like: 
```
the	O
Zionist	B-PERSON_TYPE
movement	O
```

**Comment by lfoppiano** [comment]
Sorry, this is really the last example :-) 

How `Central committee of the zionist union`  should be annotated? 

Here how we did it: 
```
he	O
served	O
as	O
a	O
member	B-TITLE
of	O
the	O
Central	B-ORGANISATION
Committee	ORGANISATION
of	O
the	O
Zionist	B-ORGANISATION
Union	ORGANISATION
in	O
Bulgaria	B-LOCATION
```

but we had the doubt of going for the whole match: 
```
Central	B-ORGANISATION
Committee	ORGANISATION
of	ORGANISATION
the	ORGANISATION
Zionist	ORGANISATION
Union	ORGANISATION
```

**Comment by kermitt2** [comment]
Yes the entity (largest mention) is the organisation here, so I would say first one.

**Comment by kermitt2** [comment]
you mean second one ?

**Comment by lfoppiano** [comment]
@kermitt2 there are two comments from me before (sorry for the confusion): I'm not sure what you refer to.

**Comment by kermitt2** [comment]
Sorry I mixed up everything ! the entity (largest mention) is the organisation here, so I would say SECOND one.
