### ISSUE TITLE
Software, how to annotate it? 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#16]
`IDEA ALM` is a software for data management from Yav Vashem,
1. how should be annotated? We've choosen `ARTIFACT`
2. should `system` also be included in the annotation? 

This would apply also for other cases like `Microsoft Word` or any software name. 

Example: 
```
Description	O
of	O
the	O
files	O
are	O
available	O
on	O
IDEA	B-ARTIFACT
ALM	ARTIFACT
system	O
at	O
Yad	B-INSTITUTION
Vashem	INSTITUTION
Archives	INSTITUTION
reading	O
room	O
and	O
on	O
the	O
Yad	B-INSTITUTION
Vashem	INSTITUTION
website	O
```

**Comment by kermitt2** [comment]
```ARTEFACT``` is for this kind of human made thingy.

"system" is super ambiguous...

If we want to specify more the ```ARTEFACT``` entity, the chosen principle is to add word senses.
