### ISSUE TITLE
new class LEGAL

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#17]
In the next piece of text there are two interesting entities: `anti-Jewish legislation` and `anti-semitic policy`. We've annotated as `LEGAL`, does it make sense? 

Example: 
```
The	O
material	O
consists	O
of	O
the	O
following	O
documentation	O
:	O
-	O
Internal	O
policies	O
of	O
Bulgaria	B-LOCATION
during	O
the	O
war	O
and	O
anti	B-LEGAL
-	LEGAL
Jewish	LEGAL
legislation	LEGAL
;	O
-	O
Implementation	O
of	O
the	O
anti	B-LEGAL
-	LEGAL
Semitic	LEGAL
policy	LEGAL
and	O
Commissariat	B-INSTITUTION
for	INSTITUTION
Jewish	INSTITUTION
Affairs	INSTITUTION
activities	O
;	O
```

**Comment by kermitt2** [comment]
For me ```LEGAL``` was to qualify a concrete piece of law like a treaty, an article, a case, etc. not for general terms like "policy". However it sounds applicable to these cases. We would need more practice and examples... 

(still no XML ah ah )

**Comment by everzeni** [comment]
To continue this discussion, an example:
> <ENAMEX type="PERSON_TYPE">Nazi</ENAMEX> policies divided the population into two categories, (...)

"policies" seems general in this context so I would tend to annotate only "Nazi":
 `<ENAMEX type="PERSON_TYPE">Nazi</ENAMEX> policies divided the population into two categories, (...)`

**Comment by kermitt2** [comment]
Yes I would do the same.

**Comment by everzeni** [comment]
What do you think about:
> Peukert quotes policy documents (...) which (...) showed the full intentions of **Nazi social policy**

I want to annotate only _Nazi_ since _social policy_ is very general. But is it really that different from _anti-semitic policy_ that we annotated as `LEGAL`?

**Comment by lfoppiano** [comment]
I'm not sure, I think it's different because `social policy` is a very generic and broad term and `anti-semitic policy` is very specific.
