### ISSUE TITLE
CREATION class

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#19]
CREATION cover `artistic creation, such as song, movie, etc.` 
Should a book title then be considered also as such?

**Comment by kermitt2** [comment]
I think yes, as long it is in natural language and not as part of a full bibliographical reference (for which the NER is not relevant).

**Comment by ebenaissa** [comment]
Should we also annotate TV Shows as CREATION ? For example in this paragraph : 

> __EU Referendum: The Great Debate__ was held at Wembley Arena on 21 June and hosted by David Dimbleby, Mishal Husain and Emily Maitlis in front of an audience of 6,000.
> 
> [272] The audience was split evenly between both sides.Sadiq Khan, Ruth Davidson and Frances O'Grady appeared for Remain.Leave was represented by the same trio as the ITV debate on 9 June (Johnson, Leadsom and Stuart).
> 
> [273] __Europe: The Final Debate__ with Jeremy Paxman was held the following day on Channel 4.

"EU Referendum: The Great Debate" refer to a political tv show (https://subsaga.com/bbc/politics/2016/eu-referendum-the-great-debate.html)

"Europe: The Final Debate" too (http://www.channel4.com/programmes/europe-the-final-debate-with-jeremy-paxman/on-demand/64596-001)

**Comment by lfoppiano** [comment]
I would annotate them as `CREATION`. Like movies, talk or tv show should be considered artistic creation (independently of the quality).
