### ISSUE TITLE
ACRONYM, when to really use them?

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#20]
The acronym class brought some ambiguity. When should be used? Most of the time acronym are referring to other entities. Should the rule be to use acronym when it's an acronym AND the entity is of no other classes? 

Or should be used in a sentence like ` the United Nation (UN) is stating that the war is bad`, `united nation` is annotated as ORGANISATION and `UN` as `ACRONYM`?

**Comment by kermitt2** [comment]
For me it's when we use an acronym that belongs to none of the other classes, e.g. DIY, BYOD, etc.

**Comment by lfoppiano** [comment]
Ahhh, OK.. This makes sense indeed! I could not find any example not related to other classes.
