### ISSUE TITLE
LOCATION specification of the region/area

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#21]
The sentences: `[...] war refugees from Russia, people repatriated from Suvalkų area and Pakruojis local rural district, local residents who have[...]` contains two additional information near the two `LOCATION` mentions. Should we expand the entitiy and add this specificity or just locate the two main entities? 

like:
```
from	O
Suvalkų	B-LOCATION
area	LOCATION
```

and  
```
Pakruojis	B-LOCATION
local	LOCATION
rural	LOCATION
district	LOCATION
```

**Comment by kermitt2** [comment]
Good question! 

I would include indeed the modifiers that qualify the location, but not the articles and prepositions.

**Comment by ebenaissa** [comment]
Just to confirm for a sentence : 

```xml
The <ENAMEX type="LOCATION">U.S.</ENAMEX> eventually establishes safe zones
west of the <ENAMEX type="LOCATION">Rocky Mountains</ENAMEX> and spends much of the next
<ENAMEX type="PERIOD">decade</ENAMEX> eradicating zombies in that region.</sentence>
```

We just annotate the rocky mountains as location without "west of" right ?

**Comment by kermitt2** [comment]
Oui... except if it is explicitly  part of the proper name like _West Mountain_.

**Comment by everzeni** [comment]
What about things like `Northern Canada` or `Coast of Honolulu`?

**Comment by kermitt2** [comment]
Same as _West Montain_ for me, it's frozen names to relatively specific places I think (they have capital letters! its a sign!).

**Comment by lfoppiano** [comment]
Yes, moreover `Northern Canada` is a well idenfied region by itself, see [here](https://en.wikipedia.org/wiki/Northern_Canada).

**Comment by everzeni** [comment]
We found the entity **Eurozone**:
> <ENAMEX type="LEGAL">Eurozone laws</ENAMEX> would not necessarily apply to non-<ENAMEX type="LOCATION">**Eurozone**</ENAMEX> <ENAMEX type="INSTITUTION">EU</ENAMEX> members and the latter would not have to bail out troubled <ENAMEX>

Do you think it's a LOCATION?

**Comment by lfoppiano** [comment]
I would say not, because we are talking about the status of being part of the Eurozone (a contract between country having the same currency). Mentioned [here](https://github.com/kermitt2/grobid-ner/issues/12#issuecomment-302629002).

**Comment by everzeni** [comment]
discussion about this in issue #12
