### ISSUE TITLE
Auxiliary police as an ORGANISATION?

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#22]
In the sentence `instructions for the auxiliary police, correspondence about foreign passports, applications from residents`, should `auxiliary police` be considered an ORGANISATION? 

```
instructions	O
for	O
the	O
auxiliary	B-ORGANISATION
police	ORGANISATION
```
I would say no because is a general mention, not a specific one (e.g. Gestapo). @kermitt2 what do you think?

**Comment by kermitt2** [comment]
Not easy... it could be view as an INSTITUTION too (as _the police_). 

Some questions to decide would be: does it correspond to an organised group of persons or rather a group of persons which share a structure/a location? Does it -on its own- represent a stable institution (INSTITUTION) or just a group of people within the institution (ORGANISATION), and third is it a random subset of an organization/institution or something established with some autonomy (like _city police_, _train police_, etc.).
