### ISSUE TITLE
Should we annotate fictive annotations

### ISSUE THREAD

**Issue by ebenaissa** [kermitt2/grobid-ner#24]
When we annotate a text from a book or a film description, should we annotate fictive entity such as (extract from the Wikipedia_worldWarZ.training.xml file) : 

`Determined to lead by example, the U.S. military reinvents itself to meet the specific strategic requirements of fighting the undead: using semi-automatic, high-power rifles and volley firing, focusing on head shots and slow, steady rates of fire (a tactic re-invented by the Indian Army during the "Great Panic"); and devising a multipurpose hand tool, the "Lobotomizer" or "Lobo"  (described as a combination of a shovel and a battle axe), for close-quarters combat.`

1) Should we annotate "Lobotomizer" and "Lobo" as `ARTIFACT` 
2) Sould we also annotate some fictive event or institution for exemple here the fictive event "the Great Panic".

**Comment by lfoppiano** [comment]
I would say Yes to both, @kermitt2 what do you think?

**Comment by kermitt2** [comment]
Agree, yes to both - the world as we tell it in all these books is a fiction anyway :D 💃
