### ISSUE TITLE
Level of precision for a PERIOD

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#25]
In the following sentence: ```Further information: Anti-Jewish legislation in prewar Nazi Germany```, should "prewar" be annotated as a PERIOD?

```xml
Further information: <ENAMEX type="LEGAL">Anti-Jewish legislation</ENAMEX> in <ENAMEX
 type="PERIOD">prewar</ENAMEX> <ENAMEX type="PERSON_TYPE">Nazi</ENAMEX> 
<ENAMEX type="LOCATION">Germany</ENAMEX>
```

**Comment by lfoppiano** [comment]
I'm not sure. 
Maybe `prewar` should not be considered a `PERIOD` named entity, when taken alone. 

I'm wondering whether we could annotate `prewar Nazi` as `PERIOD` because it refers to `before 1933` and Germany as `LOCATION`. @kermitt2 ?

**Comment by kermitt2** [comment]
Following the longest entity principle, it would be a PERIOD as a whole, e.g. 
```xml
<ENAMEX type="PERIOD">prewar Nazi Germany</ENAMEX>
```

**Comment by lfoppiano** [comment]
When we have something like `and spends much of the next decade eradicating zombies in that region.` does it make sense to annotate `decade` as `PERIOD` (= a period of 10 years).

**Comment by kermitt2** [comment]
for me yes 👍
