### ISSUE TITLE
Quotation marks included or not in the EN tag

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#26]
In the following: 
> political opponents such as <ENAMEX type="PERSON_TYPE">Marxists</ENAMEX>, <ENAMEX type="PERSON_TYPE">liberals</ENAMEX>, <ENAMEX type="PERSON_TYPE">Christians</ENAMEX> and the <ENAMEX type="PERSON_TYPE">**&quot;reactionaries&quot;**</ENAMEX> who were viewed as wayward &quot;<ENAMEX type="CREATION">National Comrades</ENAMEX>&quot;

I want to anotate "reactionaries" like the others PERSON_TYPE entities. Should I include the quotes in the tag or not? 
```xml
1) <ENAMEX type="PERSON_TYPE">"reactionaries"</ENAMEX>
```
or
```xml
2) "<ENAMEX type="PERSON_TYPE">reactionaries</ENAMEX>"
```

**Comment by lfoppiano** [comment]
From my point of view, the quotes should not be included. The presence of absence does change the significate of the class? I think not, as `reactionaries` is still a `PERSON_TYPE` class.

**Comment by kermitt2** [comment]
Yes, as a general rule in GROBID, punctuations and any similar sugar should be left outside the tagged "field".
