### ISSUE TITLE
Precision on the difference between NATIONAL and PERSON_TYPE

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#30]
I was reading the annotation guidelines about [largest entity mention](http://grobid-ner.readthedocs.io/en/latest/annotation-guidelines/#largest-entity-mention) and I'm struggling a bit to draw the line between NATIONAL and PERSON_TYPE. It says:

> Let's consider the token British. Depending on the context, British in isolation can labelled with the classes NATIONAL (when introducing a relation to Great Britain), PERSON_TYPE (for the British people) or CONCEPT (when refering to the British English language)

Regarding the _British people_, for example, do we use PERSON_TYPE only if the token _British_ is in isolation? Like:
```xml
- a <ENAMEX type="NATIONAL">British</ENAMEX> historian said this.
- a <ENAMEX type="PERSON_TYPE">British</ENAMEX> said this.
```
?

**Comment by kermitt2** [comment]
I would say, for the particular case of _British people_, we might also want to label _British_ as `PERSON_TYPE` when it is clear that we refer to the folks - not just in relation to a location. 

For instance, "the British descendants in Canada", the "British emigrants" ?  
What do you think?

**Comment by everzeni** [comment]
It makes sense, but what would be the criteria? When it refers to a human? For example in `British historian`, `British` would be annotated as `PERSON_TYPE` ?

**Comment by kermitt2** [comment]
Yes, so depending on the context if the historian studies the "ethnic" British or, by default, the country/national.  In the case of "British historian", I think it will be an historian coming from Great-Britain so it would be `NATIONAL`. I don't think we will find "British historian" in the case of an historian specialised in the history of the British folk, it would be expressed differently.

**Comment by everzeni** [comment]
So we discussed this and here is a recap:
1. PERSON_TYPE because the entity is a group of people:
```xml
- the <ENAMEX type="PERSON_TYPE">British</ENAMEX> are great people.
- the <ENAMEX type="PERSON_TYPE">British emigrants</ENAMEX>
- the <ENAMEX type="PERSON_TYPE">British people</ENAMEX> are not great
```
2. NATIONAL because it refers to the LOCATION:
```xml
a <ENAMEX type="NATIONAL">British</ENAMEX> historian
```

**Comment by everzeni** [comment]
@kermitt2 what do you think of our recap? I'm still not sure if `emigrants` and `people` are to be included in the tag here.

**Comment by kermitt2** [comment]
I would say:
- the <ENAMEX type="PERSON_TYPE">British</ENAMEX> are great people.
- the <ENAMEX type="PERSON_TYPE">British</ENAMEX> emigrants
- the <ENAMEX type="PERSON_TYPE">British</ENAMEX> people are not great

Emigrants and poeple are not named entities rather common words.

**Comment by wigdan** [comment]
For the following sentence:

`These were: additional immigration controls, especially for new <ENAMEX type="TITLE">EU members</ENAMEX>; tougher immigration rules for present <ENAMEX type="INSTITUTION">EU</ENAMEX> citizens`

We used to annotate EU as INSTITUTION, as shown above.

Now, applying the large entity match principe, we would think, it would be more appropriate to annotate the whole NP (EU citizen), and by doing so, we would consider "citizen" as PERSON_TYPE? Just (US citizen, or British citizen). Note that, However, we thought (British) in this case is NATIONAL.

`<ENAMEX type="PERSON_TYPE">EU citizens</ENAMEX>`

**Comment by kermitt2** [comment]
I think it's not the same as `British` because `British` alone is ambiguous as `PERSON_TYPE` or `NATIONAL`. `EU` alone can only be `INSTITUTION` and _citizen_ is a common name, not an entity, so the largest entity principle does not apply:

<ENAMEX type="INSTITUTION">EU</ENAMEX> citizens

**Comment by wigdan** [comment]
In a previous discussion, we decided to annotate British immigrants or British descendants as PERSONNE_TYPE
I think  immigrants and descendants are also common names just like citizens, non? 
how the policy would be in the case of British citizens?

**Comment by kermitt2** [comment]
Mmm @wigdan I am not sure I understand. _Immigrants_, _descendants_ are all common words excluded from the entity markup no? Same for _citizens_.  That's what I suggested in my messages above (5 days ago... "Emigrants and poeple are not named entities rather common words.").

**Comment by everzeni** [comment]
@kermitt2, we are a bit confused.

* When something that may be NATIONAL is used to refer to people, we annotate PERSON_TYPE: ex. `the <ENAMEX type="PERSON_TYPE">British</ENAMEX> emigrants`

* We still don't know what to do for cases where the entity refers to a group of people in adhesion with a CONCEPT (issue #29, examples in https://github.com/kermitt2/grobid-ner/issues/29#issuecomment-301034294) like `the eurosceptics held a protest`

* It seems to us the same question is valid for INSTITUTION. After all, the citizens from EU are a group of people, so why not `<ENAMEX type="PERSON_TYPE">EU</ENAMEX> citizens`?

What do you think?

**Comment by wigdan** [comment]
I also came across (Commonwealth citizens) which defines a person who has that status under British nationality law and may enjoy some privileges in the United Kingdom (Wikipedia). For instance, Sudan used to be belong to the Commonwealth countries...

So, i'm adding this suggestion  `<ENAMEX type="PERSON_TYPE">Commonwealth</ENAMEX>` 

In the case of COORDINATION, it will be helpful, please check the following sentence:

1- The `<ENAMEX type="LEGAL">European Union Referendum Act 2015</ENAMEX> dictated that only <ENAMEX type="PERSON_TYPE">British, Irish and Commonwealth</ENAMEX> citizens`

2- The `<ENAMEX type="LEGAL">European Union Referendum Act 2015</ENAMEX> dictated that only  <ENAMEX type="PERSON_TYPE">British, Irish</ENAMEX> and <ENAMEX type="INSTITUTION">Commonwealth</ENAMEX> citizens`

Note that in 2, while annotating "Commonwealth" as INSTITUTION, the COORDINATION with other named entities is somehow lost...

**Comment by lfoppiano** [comment]
@wigdan 👍 for `<ENAMEX type="PERSON_TYPE">Commonwealth</ENAMEX>`, for the second question I would keep the first proposal, `Commonwealth` is an Institution but the citisen are a group of people.

**Comment by kermitt2** [comment]
The motivation for annotating `British` differently from `EU` is that `British` alone is ambiguous between `PERSON_TYPE` and `NATIONAL`. This is not the case for `EU` which cannot alone be `PERSON_TYPE`, it is `INSTITUTION`. 

1. So when something that may be NATIONAL is used to refer to people, we annotate `PERSON_TYPE`: ex. 
```xml
the <ENAMEX type="PERSON_TYPE">British</ENAMEX> emigrants
```

2. _Citizens from EU_ are a group of people, but not a named entity because _citizens_ is a common name, and so it leaves _EU_ as the only named entity here - which is not alone a `PERSON_TYPE`, so 
```xml
<ENAMEX type="INSTITUTION">EU</ENAMEX> citizens
```

3. Suppose we have `EU British citizen`, _British_ is `PERSON_TYPE` in this context and a named entity, so from the largest entity principle we have:
```xml
<ENAMEX type="PERSON_TYPE">EU British</ENAMEX> citizens
```

4. `Commonwealth` is like the `EU` an `INSTITUTION`. Like `EU`, `Commonwealth` alone never refer to `PERSON_TYPE`, it's an institution (like the EU and many institutions, this institution grants some rights to its members, but an institution is more than its members). So the annotation in your example would be the second, given that citizen is common name:

```xml
The <ENAMEX type="LEGAL">European Union Referendum Act 2015</ENAMEX> dictated that only <ENAMEX type="PERSON_TYPE">British, Irish</ENAMEX> and <ENAMEX type="INSTITUTION">Commonwealth</ENAMEX> citizens. 
```

**Comment by everzeni** [comment]
@kermitt2 thanks, 
so if I understand correctly, things like `Eurosceptic` could also be PERSON_TYPE when referring to people, because like `British` it can be ambiguous (between CONCEPTUAL and PERSON_TYPE)?

**Comment by everzeni** [comment]
note for doc, this is related to https://github.com/kermitt2/grobid-ner/issues/29#issuecomment-302898533
