### ISSUE TITLE
compound NPs labelled with "dash"

### ISSUE THREAD

**Issue by wigdan** [kermitt2/grobid-ner#31]
How would you annotate this:

Nobel prize-winning economist 

"Nobel prize" alone would be tagged as AWARD
But what makes it little complicated is the "dash" in "Nobel prize-winning", 
furthermore, should we annotate economist within this context or leave it out of the entire nominal phrase "Nobel prize-winning economist"

**Comment by kermitt2** [comment]
I think we can annotate like this for non-agglutinative languages when we have a dash:

```xml
<enamex type="AWARD">Nobel prize</enamex>-winning economist
```

_Economist_ or other profession name is not seen as a named-entity in our set of classes, so I think we should not annotate the whole NP.
