### ISSUE TITLE
TITLE

### ISSUE THREAD

**Issue by wigdan** [kermitt2/grobid-ner#33]
` and now exports oil from a reserve under <ENAMEX type="INSTALLATION">Windsor Castle</ENAMEX> where the <ENAMEX type="TITLE">Queen</ENAMEX> held out for the war 
`

above is an example where we could annotate "QUEEN" as TITLE,
would you all agree?

**Comment by everzeni** [comment]
we can answer this question in the other TITLE thread #12

**Comment by lfoppiano** [comment]
Yes, queen is a `TITLE`

**Comment by ebenaissa** [comment]
```xml
whichwere officially placed under the <!-- check if this is a title -->direction of the <ENAMEX type="TITLE">National State Archivist</ENAMEX> (who holds his office in the <ENAMEX type="INSTITUTION">National Archives</ENAMEX>)
``` 

Should we include general profession (in this example "Archivist", it can also be scientist, engineer, ...) as TITLE ?

**Comment by lfoppiano** [comment]
I close this issue as the discussion has been continued on #12
