### ISSUE TITLE
consistency analysis

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#35]
In order to verify roughly that we are not changing the way we annotate over time, we have agreed to try to see if having a small script analysing all the input file can be helpful. 

The idea is the following, the script collect all the annotations and inform when the same token has been annotated with different classes. For example if `President of the US` has been annotated as `PERSON` and as `PERSON-TYPE`. 

The idea is not to check the context, but purely the tuple `(token, class)`so we know that we might see many false positive. 

the script has to be something `script inputdirectory` and should print out something like: 
```
President of the US: 
PERSON: preview of a chunk of sentence with the annotation PERSON (including the XML)
PERSON_TYPE: preview of a chunk of sentence with the annotation PERSON_TYPE (including the XML)
```

**Comment by ebenaissa** [comment]
I'm currently doing it in Python 2.7. The way of how i'm doing it is just parse each xml files of the inputdirectory to catch all ENAMEX tag and put in a dictionary the token (annotation) as the key and classes as the value. 
And i will just show all keys with multiple values.

Tell me if there is a misunderstanding or if there is a better way for doing this.

I'm finishing it probably tomorrow.

**Comment by lfoppiano** [comment]
Looks good for me, you can use a Set as value of the map so you only add unique values
