### ISSUE TITLE
Foreign words

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/grobid-ner#37]
I have a doubt about the foreign words: shall we introduce an additional class to annotate the foreign words?
 
The problem is apparent from a another project which has just started, where we have the requirement to annotate foreign words in French texts because they need to be transcribed differently in Braille (as in general all proper names which require full Braille, common words are transcribed with abbreviated Braille). 

If we introduce a class for foreign words, we will have conflicts with the _actual_ class of the term, so we would need to decide:

- either as a general rule, any foreign words (not in a regular dictionary of the language) should be annotated with a class `FOREIGN_WORD`, which takes priority over every alternatives,

- or we annotate the foreign words with their "normal" entity class when relevant, and with a class `FOREIGN_WORD` in all the other cases.

I would tend to choose the second choice.

**Comment by lfoppiano** [comment]
@kermitt2 I'm also in favour of the second choice. 

I'm wondering how can then the information about a foreign word be extracted for tokens annotated with their relevant class. 

I'm thinking some sligltly alternatives, but they are not convincing: like having a second attribute or recognise the foreign words as a further step.

**Comment by kermitt2** [comment]
Yes we could also do that indeed as first or secondary step, simply classify if we have a foreign word token or not - with character n-gram it is reliable. I was thinking to introduce n-gram related deviation in the list of features for addressing that, so that, with the CRF, we can also capture larger sequence aspects related to the mixing of several languages in a text. 

But as you suggest we could imagine a third option which is a general attribute to indicate if we have a foreign word token or not, independent from the named entity classes, so leaving a `FOREIGN_WORD` class out of the picture.

**Comment by lfoppiano** [comment]
Yes, I think some different layer would be compatible with the current annotations and independent as well.

**Comment by kermitt2** [comment]
Ok let's stick with this - foreign word will be an extra attribute orthogonal to the entity class.

**Comment by ebenaissa** [comment]
```xml
[...] also known as the <ENAMEX type="EVENT">Shoah</ENAMEX> (<ENAMEX type="CONCEPT">
Hebrew</ENAMEX>: <ENAMEX type="EVENT">השואה</EVENT>, <ENAMEX type="EVENT">HaShoah</EVENT>,
"the catastrophe")
```

We said (waiting for confirmation in issue 27) that we annotate foreign words when it's not common words (like in this example `"the catastrophe"`) but what about foreign words written in other than latin character (like` "השואה"`) ?

**Comment by kermitt2** [comment]
When possible, I think it is consistent to annotate them, independently if they are with latin or non-latin characters.
