### ISSUE TITLE
CONLL to XML conversion

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#38]
We need to convert the old CONLL files to XML :-)

**Comment by lfoppiano** [comment]
@kermitt2 could you please check whether the files I have pushed from 75f338b are acceptable from the point of view of the structure (we'll check the content later)?

**Comment by kermitt2** [comment]
Yes all right :+1:  

Sense value could be introduced by an attribute `@subtype`

**Comment by lfoppiano** [comment]
OK, in fact `type` and `sense` are not elegant. I will change that. 

We should also find a better name for `ENAMEX` at some point :-)

**Comment by kermitt2** [comment]
well it's just to be compatible with Le Monde corpus - I would say it doesn't really make sense to modify this crappy format to something in-house, but rather at some point to move to TEI. Let's keep it crappy to remember to convert it to TEI and release a nice CC-0 data set :D
