### ISSUE TITLE
MEASURE, PERIOD or nothing?

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#41]
(I open a new issue to avoid mixing too many question in one thread, but this may be related to #13)

> a boycott (...) which was the first national <ENAMEX type="CONCEPTUAL">antisemitic</ENAMEX> campaign, initially planned for **a week**, but called off after **one day** owing to lack of popular support.

I don't know what to do with _**a week**_ and _**one day**_:
```xml
1) - <ENAMEX type="MEASURE">a</ENAMEX> week
- <ENAMEX type="MEASURE">one</ENAMEX> day

2) - <ENAMEX type="MEASURE">a week</ENAMEX>
- <ENAMEX type="MEASURE">one day</ENAMEX>

3) - <ENAMEX type="PERIOD">a week</ENAMEX>
- <ENAMEX type="PERIOD">one day</ENAMEX>

4) nothing or another thing : )
```

**Comment by kermitt2** [comment]
For me `PERIOD`, solution 3).
Any `PERIOD` is actually a measurement (it is a quantified measure of time), but the opposite is not true, so `PERIOD`, which is more specific, wins.
