### ISSUE TITLE
question about INSTALLATION

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#42]
1) What to do with concentration camps names?
We were thinking maybe INSTALLATION but it seems weird, and there are diverse cases, sometimes the camps are designated only by their location name, for example. Here are some occurrences:

- _<ENAMEX type="INSTALLATION">Lager Nordhausen</ENAMEX>_
- _<ENAMEX type="LOCATION">Mittelbau-Dora</ENAMEX>_
- _<ENAMEX type="LOCATION">Mauthausen-Gusen</ENAMEX> concentration camp_

and ghetto names, for example the _Warsaw Ghetto_?

**Comment by kermitt2** [comment]
I think it indeed all refer in context to the facilities (not the cities), so `INSTALLATION`.

I would say a ghetto name is a `LOCATION`, it's a city district.

**Comment by everzeni** [comment]
I reopen this thing to ask a question in the context of the second layer annotation, regarding mentions of concentration camps 

In the file Wikipedia_holocaust.1.en.training.2layers.xml, there is this sentence: 
> Some [physicians] carried out experiments at Auschwitz, Dachau, Buchenwald, Ravensbrück, Sachsenhausen, and Natzweiler concentration camps

Annotated in the first annotation as:

```xml
Some [physicians] carried out experiments at <ENAMEX type="INSTALLATION">Auschwitz, 
Dachau, Buchenwald, Ravensbrück, Sachsenhausen, and Natzweiler concentration camps</ENAMEX>
```
**In this sentence, I'm not sure how to annotate subtypes:**

```xml
Some carried out experiments at <ENAMEX type="INSTALLATION"><ENAMEX subType="2" 
type="LOCATION">Auschwitz</ENAMEX>, <ENAMEX subType="2" type="LOCATION">
Dachau</ENAMEX> (...), and <ENAMEX subType="2" type="INSTALLATION">Natzweiler
concentration camps</ENAMEX></ENAMEX>
```
or just

```xml
Some carried out experiments at <ENAMEX type="INSTALLATION">Auschwitz, Dachau, and 
Natzweiler concentration camps</ENAMEX>

(since it would be wrong to annotate only LOCATION subtypes)
``` 
?

thank you : )

----------------------------------------------------
----------------------------------------------------
Reminder about LOCATION/INSTALLATION with concentration/extermination camps:

1) `Auschwitz, Dachau`, etc. were primarily LOCATIONs, so when they are alone and clearly referring to the locations, we annotate them as LOCATIONs, for example: 
```[extermination camps] were established at <ENAMEX type="LOCATION"><ENAMEX subType="2" type="LOCATION">Auschwitz</ENAMEX>, <ENAMEX subType="2" type="LOCATION">Belzec</ENAMEX> (...), and <ENAMEX subType="2" type="LOCATION">Treblinka</ENAMEX></ENAMEX>```

2) more often, we find mentions of the concentration/extermination camps themselves, with or without the words "camp"/"concentration camp", and they're INSTALLATION for example (fictive example): 
```they were killed at <ENAMEX type="INSTALLATION">Auschwitz concentration camp</ENAMEX>```

**Comment by kermitt2** [comment]
Given the subtype is quite clear, I would say:

```Some carried out experiments at <ENAMEX type="INSTALLATION"><ENAMEX subType="2" 
type="LOCATION">Auschwitz</ENAMEX>, <ENAMEX subType="2" type="LOCATION">
Dachau</ENAMEX> (...), and <ENAMEX subType="2" 
type="LOCATION">Natzweiler</ENAMEX>concentration camps</ENAMEX></ENAMEX>```

**Comment by everzeni** [comment]
ok but we can't annotate the subtypes if not one of them is the same as the general type (here the subtypes would all be LOCATION whereas the general type is INSTALLATION). So it would be the second option (```Some carried out experiments at <ENAMEX type="INSTALLATION">Auschwitz, Dachau, and Natzweiler concentration camps</ENAMEX>```)

is it ok?

**Comment by kermitt2** [comment]
mmm I don't understand why we can't annotate the subtypes if not one of them is the same as the general type, it's the general case no? like `president of the United State`

**Comment by everzeni** [comment]
From what I understood about this subtype annotation, in that case that would be ok because in `president of the United State`, the general type is TITLE and the first subtype is also TITLE:

```xml
<ENAMEX type="TITLE"><ENAMEX subType="2" type="TITLE">president</ENAMEX>
 of the <ENAMEX subType="2" type="LOCATION"> United State</ENAMEX></ENAMEX>
```

**Comment by kermitt2** [comment]
Well if we follow this logic then `concentration camps` is the installation subtype: 

```xml
Some carried out experiments at <ENAMEX type="INSTALLATION"><ENAMEX subType="2" 
type="LOCATION">Auschwitz</ENAMEX>, <ENAMEX subType="2" type="LOCATION">
Dachau</ENAMEX> (...), and <ENAMEX subType="2" 
type="LOCATION">Natzweiler</ENAMEX> <ENAMEX subType="2" 
type="INSTALLATION">concentration camps</ENAMEX></ENAMEX>```

however I think it does not make much sense, as concentration camps is not a named entity alone. Maybe not for `President of the United States` because we have a title indeed, but it's very common cases imho, the `university of Washington`, `alpha B2 proteins`, the `United NAtion headquarters`, and so on... For nested entities, often the actual head of the NE is not a NE, it's a common name.

**Comment by everzeni** [comment]
> "For nested entities, often the actual head of the NE is not a NE, it's a common name"
absolutely, and in those case we didn't annotate subtypes, is that wrong?

**Comment by kermitt2** [comment]
Well I would not say `wrong` :D 
but I don't see why - the subtype is easy and useful to annotate: 

```xml
 <ENAMEX type="INSTALLATION"><ENAMEX type="ORGANISATION">United Nation</ENAMEX> headquarters</ENAMEX>```

same for the concentration camps, nice to have the actual locations in the nested NE.

But did I misunderstand or overlook something? What was the reason to ignore these nested NE?

**Comment by lfoppiano** [comment]
The goal as I see it is to have two layers, the larger entities matching (type: "lsm") and 'normal' annotations (no type). 

For our purposes (grobid-ner) they cannot be used at the same time. In combination with the Idillia corpus we should use the `normal` annotations, thought the LSM could be used as well for other tasks (though the data available is not a lot).

The first idea is to split the longest entity match that are separated by commas, then try to split composed annotations (e.g. `The President of the United States Barak Obama`). 

On the other hand, if we go too much in details, we end up getting a lot of `LOCATION`, `PERSON` and `ORGANISATION` and loosing a lot of `EVENT`, `CONCEPT`, `TITLE` and so on, therefore in the effort to find a balance, the rule "do not split when the outer annotation is lost" was consistent enough.

The example we would loose a lot of `EVENTS` if splitting in the inner annotations as they often contains a `LOCATION`, a `PERIOD` etc.

**Comment by kermitt2** [comment]
The actual problem of not annotating consistently the nested NE is that we could not train two different models, one for "largest" NE, and one in cascade for the nested NE - the nested one would produce false positive and errors because the annotation is dependent on the largest type (it should be context free like a context free grammar).

**Comment by lfoppiano** [comment]
I see your point. Given the time available left, the attempt was more to "amend" the first version done in the first three months (many annotations were matching just too much) to be compatible with Idillia corpus. 
The `subType` still have to be reassigned only to the Largest Entity Matching entities.
