### ISSUE TITLE
question about MEASURE

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#43]
Should we include things like _more than_ or _over_ inside a MEASURE tag, examples:

> **Over <ENAMEX type="MEASURE">7,000</ENAMEX>** <ENAMEX type="PERSON_TYPE">Jewish</ENAMEX> shops and **more than <ENAMEX type="MEASURE">1,200</ENAMEX>** synagogues (roughly <ENAMEX type="MEASURE">two-thirds</ENAMEX> of the synagogues in areas under <ENAMEX type="NATIONAL">German</ENAMEX> control) were damaged or destroyed.

**Comment by kermitt2** [comment]
Yes these are markers of the intervals necessary to qualify the `MEASURE`.
