### ISSUE TITLE
Generic terms which are entities in context

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#45]
Sometimes a generic word is referring to an entity in the context. Do you think we should annotate them? For example:
1) `war` as EVENT?
> Germany was losing the **war**

2) `world` as LOCATION?
> broader trends in **world** history
> bringing the first credible news to the **world** of the mass murder that was taking place there

**Comment by lfoppiano** [comment]
I'm not sure, leave it out, unless @kermitt2 disagree :-)

**Comment by kermitt2** [comment]
Yes I agree with Luca to not annotate them - it's a referring expression, per se not a named entity. In practice, this will be tackled by the disambiguation process.
