### ISSUE TITLE
question about parenthesis

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#47]
We're not sure what to do with entities between parenthesis. There are different cases:
1) largest entity match principle where the second entity is between parenthesis, example:
```xml
<ENAMEX type="EVENT">Kristallnacht (1938)</ENAMEX>
or
<ENAMEX type="EVENT">Kristallnacht</ENAMEX> (<ENAMEX type="PERIOD">1938</ENAMEX>)
?
```

2) both entities refer to the same thing:
```xml
by the <ENAMEX type="INSTITUTION">Sturmabteilung</ENAMEX> (<ENAMEX type="INSTITUTION">SA</ENAMEX>)
 and the <ENAMEX type="INSTITUTION">Schutzstaffel</ENAMEX> (<ENAMEX type="INSTITUTION">SS</ENAMEX>)

or

run by the <ENAMEX type="INSTITUTION">Sturmabteilung</ENAMEX> (SA)</ENAMEX>
 and the <ENAMEX type="INSTITUTION">Schutzstaffel (SS)</ENAMEX>

?
```

**Comment by lfoppiano** [comment]
For the number (2) I would say the second one. They would be referring to the same entity for `Sturmabteilung` and `SS`. 

The number (1) I would say the second because 1938 is partially independent from the name `Kristallnacht`, in fact, what's the sentence?

**Comment by ebenaissa** [comment]
I'm ok with Luca for the number (2).
For the number (1) it appears as a title of a part (see bellow), but i would also not including it for the same reason.
```xml
<sentence xml:id="P76E0"><ENAMEX type="EVENT">Kristallnacht (1938)</ENAMEX></sentence>
```

**Comment by kermitt2** [comment]
I would applied the largest match principle in the two cases:

```xml
<ENAMEX type="EVENT">Kristallnacht (1938)</ENAMEX>
```
(date is an adjunct to the event)

```xml
run by the <ENAMEX type="INSTITUTION">Sturmabteilung (SA)</ENAMEX>
 and the <ENAMEX type="INSTITUTION">Schutzstaffel (SS)</ENAMEX>
```
