### ISSUE TITLE
formatting issue

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#48]
In the Wikipedia files, the references to citations (numbers between brackets like `[123]`) are not to be annotated and we just ignored them. In the following case normally I would have put together in one PERIOD the 4 last periods:
```xml
BBC and The New York Times</ENAMEX> published material from the <ENAMEX 
type="CREATION">Vrba-Wetzler report</ENAMEX> on <ENAMEX type="PERIOD">15 
June</ENAMEX>,[279] <ENAMEX type="PERIOD">20 June, 3 July</ENAMEX>[280] and <ENAMEX 
type="PERIOD">6 July</ENAMEX>[281] <ENAMEX type="PERIOD">1944</ENAMEX>
```
can we delete the references or just let them among the big PERIOD tag, or let it as is?

**Comment by kermitt2** [comment]
I suggest to delete them. 
In practice, the references are well identified by GROBID core, and grobid-ner will run only on text where the references are already prune out / ignored.

**Comment by lfoppiano** [comment]
@kermitt2 What do you mean with reference? 
do you mean the list at the end of the article with the list of bibliographical references but also the numbers between brackets? So in the first case, everything should be removed, in the second case only the number, correct? 

I'm asking in relation with #52

**Comment by kermitt2** [comment]
Well I reused the term used by @everzeni, so meaning the same (I am flexible :D ). In general, and in GROBID in particular, I call that _reference markers_, to distinguish more clearly the labels used to refer to a reference (_[34]_, _(Foppiano and al., 2017)_), from the full references (the string usually in the reference section at the end of the article or in foot notes).

**Comment by lfoppiano** [comment]
OK so: 
 - references are removed (e.g. _[34], (Foppiano and al., 2017)_) - usually they are lists of items)
 - references markers are removed _when in the middle of named entities_ (e.g.  _[...] on <ENAMEX type="PERIOD">15 June</ENAMEX>,[279] <ENAMEX type="PERIOD">20 June, 3 July</ENAMEX>[280] and [..]_

Does this makes sense?

**Comment by everzeni** [comment]
I had understood that all references markers were to be removed, so that's what we did, and not only the ones in the middle of named entities. Every references markers constituted by numbers between brackets have been removed.

**Comment by everzeni** [comment]
so as told by @kermitt2 in Slack:

> all references markers ( and reference strings) will be handled by ther specific parser, so they would need to be all removed to avoid interring with a NER model for "text"
