### ISSUE TITLE
wrong sentence split in the automatic annotation

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#49]
In the following part, `Jehovah's` and `Witnesses` should be together. 
```xml
		<p xml:lang="en" xml:id="P321">
				<sentence xml:id="P321E0"><ENAMEX type="PERSON_TYPE">Jehovah&
apos;s</ENAMEX></sentence>
			</p>
			<p xml:lang="en" xml:id="P322">
				<sentence xml:id="P322E0"><ENAMEX 
type="PERSON_TYPE">Witnesses</ENAMEX> 	<ENAMEX type="MEASURE">2,500–5,000</ENAMEX> 
	[315]</sentence>
			</p>
```

We don't know what to do without modifying the sentences tagging... What do you think?

**Comment by lfoppiano** [comment]
I think this is text comes from a table (I'd do what we decide to do in #50)

<img width="1163" alt="screen shot 2017-06-10 at 09 47 39" src="https://user-images.githubusercontent.com/15426/27001115-f23ef5fe-4dc1-11e7-837d-f4260349d8e6.png">
