### ISSUE TITLE
Tables from Wikipedia

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#50]
There are tables in Wikipedia, is it correct to annotate them like this (the table gives numbers about deads by Country, population (estimated before/number of people killed/percentage):

```xml
<p xml:lang="en" xml:id="P333">
				<sentence xml:id="P333E0"><ENAMEX type="LOCATION">Poland</ENAMEX> <ENAMEX type="MEASURE">	3,300,000 	3,000,000 	90</ENAMEX></sentence>
			</p>
			<p xml:lang="en" xml:id="P334">
				<sentence xml:id="P334E0"><ENAMEX type="LOCATION">Baltic</ENAMEX> countries <ENAMEX type="MEASURE">253,000 	228,000 	90</ENAMEX></sentence>
			</p>
			<p xml:lang="en" xml:id="P335">
				<sentence xml:id="P335E0"><ENAMEX type="LOCATION">Germany and Austria</ENAMEX> <ENAMEX type="MEASURE">	240,000 	210,000 	90</ENAMEX></sentence>
			</p>
```
what do you think we should do with this?

**Comment by lfoppiano** [comment]
I think tables should be either removed, or, maybe we should considered each element as a separate item?

**Comment by lfoppiano** [comment]
OK remove the tables from the file. I did the same for the new file I've added.
