### ISSUE TITLE
Stock market indexes (MEASURE, BUSINESS, other ?)

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#54]
Hello,

How should we annotate Stock exchange indexes like CAC40, US Dow Jones, FTSE 100? Even though it's related to BUSINESS, I'm not sure it's the right class for it. Some examples from the files:

- the <ENAMEX type="????">**FTSE 100**</ENAMEX> showed a steady decline
- the <ENAMEX type="????">**FTSE 100**</ENAMEX> companies
- the <ENAMEX type="????">**US Dow Jones Industrial Average**</ENAMEX> dropped nearly <ENAMEX type="MEASURE">450</ENAMEX> points

Wikipedia definition:
> A stock index or stock market index is a measurement of the value of a section of the stock market. It is computed from the prices of selected stocks (typically a weighted average).

**Comment by lfoppiano** [comment]
What about using `UNKNOWN`? They seems to be very specific entities, which are not part of any other class

**Comment by kermitt2** [comment]
This should be normally currently `CONCEPT`, which is fine I think for economical index and bond (for instance the text excerpt with `CETES` index in the NERD demo).

**Comment by everzeni** [comment]
also, from Slack: Credit ratings like AA1, AA+ are MEASURE
