### ISSUE TITLE
mvn clean install not working

### ISSUE THREAD

**Issue by karthinuk107** [kermitt2/grobid-ner#56]
Hi All,

I followed the Documentation but i end up with following Error

$ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.grobid:grobid-ner:0.4.2-SNAPSHOT: Failure to find org.grobid:grobid-parent:pom:0.4.2-SNAPSHOT in file:///${basedir}/lib/ was cached in the local repository, resolution will not be reattempted until the update interval of 3rd-party-local-repo has elapsed or updates 
are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.grobid:grobid-ner:0.4.2-SNAPSHOT (/home/karthi_vincent/Factbot-simplest/grobid/grobid-ner/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.grobid:grobid-ner:0.4.2-SNAPSHOT: Failure to find org.grobid:grobid-parent:pom:0.4.2-SNAPSHOT in file:///${basedir}/lib/ was cached in the local repository, resolution will not be reattempted until the update interval of 3rd-party-local-repo has elapsed or upda
tes are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by lfoppiano** [comment]
HI @karthinuk107. 
     Thanks for the report, not long ago we released grobid version 0.4.2 and the pom.xml in grobid-ner wasn't updated to point to the latest master version. 

Try to pull the latest changes and let me know if this solves the problem.

**Comment by karthinuk107** [comment]
Hi Ifoppiano,

Thanks for immediate response.the Issues has been resolved, but i got a another issues

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.859 s
[INFO] Finished at: 2017-08-29T07:43:16+00:00
[INFO] Final Memory: 12M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project grobid-ner: Could not resolve dependencies for project org.grobid:grobid-ner:jar:0.4.2-SNAPSHOT: The following artifacts could not be resolved: org.grobid:grobid-core:jar:0.4.2-SNAPSHOT, org.grobid:grobid-trainer:jar:0.4.2-SNAPSHOT: Could not find artifact org.grob
id:grobid-core:jar:0.4.2-SNAPSHOT in 3rd-party-local-repo (file:////home/karthi_vincent/Factbot-simplest/grobid/grobid-ner/lib/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by lfoppiano** [comment]
This is very strange, because I have updated all the dependencies and they are now pointing to version 0.4.3-SNAPSHOT. Did you run `git pull` from grobid-ner directory? 

If so, could you paste here your `grobid-ner/pom.xml`? It should look like [this](https://github.com/kermitt2/grobid-ner/blob/master/grobid-ner/pom.xml#L44).

**Comment by karthinuk107** [comment]
Hi Ifoppiano,

Yeah now issues on 0.4.3,but another issues i am facing
mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building grobid-ner 0.4.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ grobid-ner ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ grobid-ner ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ grobid-ner ---
[INFO] Compiling 30 source files to /home/karthi_vincent/Factbot-simplest/grobid/grobid-ner/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/karthi_vincent/Factbot-simplest/grobid/grobid-ner/src/main/java/org/grobid/core/features/FeaturesVectorNER.java:[298,30] error: cannot find symbol
[ERROR]   symbol:   variable YEAR
  location: variable featureFactory of type FeatureFactory
/home/karthi_vincent/Factbot-simplest/grobid/grobid-ner/src/main/java/org/grobid/core/features/FeaturesVectorNERSense.java:[322,30] error: cannot find symbol
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.504 s
[INFO] Finished at: 2017-08-30T06:30:41+00:00
[INFO] Final Memory: 20M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project grobid-ner: Compilation failure: Compilation failure:
[ERROR] /home/karthi_vincent/Factbot-simplest/grobid/grobid-ner/src/main/java/org/grobid/core/features/FeaturesVectorNER.java:[298,30] error: cannot find symbol
[ERROR] symbol:   variable YEAR
[ERROR] location: variable featureFactory of type FeatureFactory
[ERROR] /home/karthi_vincent/Factbot-simplest/grobid/grobid-ner/src/main/java/org/grobid/core/features/FeaturesVectorNERSense.java:[322,30] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by karthinuk107** [comment]
Hi Ifppiano,

The issues has been solved now,

I tried to start the server, but i am getting error

:~/Factbot-simplest/grobid/grobid-ner$ mvn -Dmaven.test.skip=true jetty:run-war
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 42.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 65.5 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.782 s
[INFO] Finished at: 2017-08-30T07:09:34+00:00
[INFO] Final Memory: 15M/372M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/karthi_vincent/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by lfoppiano** [comment]
Hi @karthinuk107 
    that's normal because there is no web service on top of the grobid-ner module. 
The module grobid-ner is currently used via the java API in a programmatic way, so there is not a java API (you could implement it, though ;-) ). 

Luca

**Comment by kermitt2** [comment]
The web API for grobid-ner is provided by _entity-fishing_, see https://github.com/kermitt2/nerd
when sendind a query to entity-fishing with the parameter `"onlyNER": true`, only grobid-ner is applied, you can have a look at the [documentation](http://nerd.readthedocs.io/en/latest/restAPI.html#response).

**Comment by lfoppiano** [comment]
Oups :-) @kermitt2 is right. Sorry I forgot about that :-)

**Comment by lfoppiano** [comment]
@karthinuk107 If this issue has been solved please close it, so we know what's left. ;-)
