### ISSUE TITLE
Italian NER

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#58]
I've found this corpus http://ontotext.fbk.eu/icab.html maybe one day we could have a look if it's worth it investing time on it to build a NER system for italian...

**Comment by kermitt2** [comment]
Non compatible license :( 
This corpus is really very small, not sure it is worth experimenting with it anyway.  
We should make clear at some point that only the English model is free to use and reuse, the French model is actually also limited to research purposes.

**Comment by lfoppiano** [comment]
OK :-)
