### ISSUE TITLE
Doc instructions out of sync.

### ISSUE THREAD

**Issue by mitchelldehaven** [kermitt2/grobid-ner#68]
Based on my previously solved issue, I assume that everything is being converted to gradle for builds. As a heads up (although this may be in the process of being converted) Grobid-ner master branch seems to be no longer using maven, but doc instructions (https://grobid-ner.readthedocs.io/en/latest/build-and-install/ under "Grobid NER Settings") have build instructions listed as maven. Also, doc instructions include copying "grobid-ner" and model files from "grobid-home/models*" to "grobid", which also appear to no longer be applicable.

**Comment by kermitt2** [comment]
Thank you @mitchelldehaven everything should be updated with commit edda070d4eb3c133684ce5de6135a4c535d85850
