### ISSUE TITLE
Questions on training data creation

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#7]
The phrase: `called " emergency brake" which would have allowed the UK to withhold social benefits to new immigrants for the first four years after they arrived;`

How `first four years` shall be annotated? 
```
the	O
first	O
four	B-MEASURE
years	O
```
or 
```
the	O
first	B-PERIOD
four	PERIOD
years	PERIOD
```

**Comment by kermitt2** [comment]
Second, I would say! What's important here is that it's a time expression. 

Good thing to put in some annotation guidelines ;)

**Comment by lfoppiano** [comment]
Here another example `The first medical experimentation on humans and ethnic cleansing by Germans	took place in the death camps of German	South-West Africa during the Herero	and	Namaqua	 Genocide.`

I have annotated it in the following way, does it make sense? 
```
The	O
first	O
medical	O
experimentation	O
on	O
humans	O
and	O
ethnic	O
cleansing	O
by	O
Germans	B-PERSON_TYPE
took	O
place	O
in	O
the	O
death	O
camps	O
of	O
German	B-NATIONAL
South	B-LOCATION
-	LOCATION
West	LOCATION
Africa	LOCATION
during	O
the	O
Herero	B-EVENT
and	EVENT
Namaqua	EVENT
Genocide	EVENT
.	O
```

**Comment by kermitt2** [comment]
The only problem I see is the "German South-West Africa" - following the largest entity mention principle all the mention is a LOCATION, so:

```
of	O
German	B-LOCATION
South	LOCATION
-	LOCATION
West	LOCATION
Africa	LOCATION
during	O
```

"German South-West Africa" is the full name of the German colony before the WW1.

**Comment by lfoppiano** [comment]
Question: 
The sentence `In 2014, the SNCF, the French state-owned railway company, was compell to allocate $60 million to America Jewish Holocaust survivor for its role in the transport of deportees to Germany.`

How `America Jewish Holocaust survivors` can be annotated? 

case 1. 
```
American	B-NATIONAL
Jewish	B-PERSON_TYPE
Holocaust	B-CONCEPT
survivors	O
```

case 2: 
```
American 	B-PERSON_TYPE
Jewish	        PERSON_TYPE
Holocaust	PERSON_TYPE
survivors         PERSON_TYPE
```

**Comment by kermitt2** [comment]
As we use the largest entity principle, I would say it is case 2 for sentence one.

For sentence 2, the class for a law or a convention would be CONCEPT I think, but this is actually a case for which we could add a new NER class called LEGAL.
